# Generated by Django 4.0.6 on 2022-07-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='memebers',
            new_name='members',
        ),
    ]
